import './style.css';

const app = document.querySelector('#app');
const turnstileSiteKey = import.meta.env.VITE_TURNSTILE_SITE_KEY || '';
const demoMode = import.meta.env.VITE_DEMO_MODE === 'true';
const state = { view: 'home', stop: localStorage.getItem('lastStop') || '', route: '', data: null, loading: false, error: '', authenticated: false, verifying: false, refreshIn: 60, timer: null, installPrompt: null, showLater: false };
const modules = [
  ['A','Arrivo Guide','Compare bus, Luas, rail, walking and taxi options in one clear journey.','Journey planning','yellow'],
  ['S','StopSure','Confirm the right stop, platform and direction before you set off.','Direction confidence','cyan'],
  ['B','BusMatch','Recognise the service you need when several vehicles approach together.','Vehicle matching','blue'],
  ['P','Pulse','See disruptions, delays and network health before they affect your trip.','Service updates','coral'],
  ['G','Guardian','Stay reassured with step-by-step progress and alerts before your stop.','Journey reassurance','green'],
  ['V','Passenger Voice','Share structured feedback that helps make everyday travel better.','Passenger feedback','violet']
];

function escapeHtml(value = '') { return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;'); }

function render() {
  app.innerHTML = `<a class="skip-link" href="#main-content">Skip to main content</a><div class="site-shell">${header()}<main id="main-content">${state.view === 'live' ? liveView() : homeView()}</main>${footer()}</div>`;
  bindEvents();
}

function header() {
  return `<header class="topbar"><a class="brand" href="#" data-view="home" aria-label="ArrivoGo home"><span class="brand-mark" aria-hidden="true"><span></span></span><span><strong>ARRIVO<span>GO</span></strong><small>DUBLIN, MADE SIMPLE</small></span></a><nav aria-label="Main navigation"><a href="#live" data-view="live">Live arrivals</a><a href="#guide">Plan a journey</a><a href="#platform">Our platform</a></nav><div class="top-actions">${state.installPrompt ? '<button id="install-app" class="install-button">Install app</button>' : ''}<span class="network-live"><i></i> DUBLIN LIVE</span><button class="menu-button" aria-label="Open live arrivals" data-view="live">GO</button></div></header>`;
}

function homeView() {
  return `<section class="hero" aria-labelledby="hero-title"><div class="hero-grid"><div class="hero-copy"><p class="kicker"><span></span> ONE CITY. EVERY WAY TO MOVE.</p><h1 id="hero-title">Every way around Dublin. <em>One simple app.</em></h1><p class="hero-intro">Compare buses, Luas, rail, walking and taxis in one journey—with live updates, clear directions and affordable choices.</p><div class="hero-actions"><button class="button primary" data-view="live">Check live departures <b>→</b></button><a class="button secondary" href="#guide">Plan my journey <b>↗</b></a></div><ul class="trust-list" aria-label="ArrivoGo benefits"><li><i>✓</i> Live NTA data</li><li><i>✓</i> Driver-built</li><li><i>✓</i> Made for everyone</li></ul></div><div class="network-card" aria-label="Example multimodal journey"><div class="map-grid" aria-hidden="true"></div><span class="map-label label-centre">CITY CENTRE</span><span class="map-label label-home">YOU</span><div class="route-line route-one"></div><div class="route-line route-two"></div><div class="map-node node-home">●</div><div class="map-node node-luas">L</div><div class="map-node node-city">◎</div><div class="journey-card"><div><span class="mode-icon">L</span><span><small>FASTEST ROUTE</small><strong>Green Line + Walk</strong></span></div><strong>28 <small>MIN</small></strong></div><div class="live-float"><i></i><span><small>NETWORK STATUS</small><strong>Services running normally</strong></span></div></div></div><div class="mode-strip" aria-label="Transport modes compared">${mode('BUS','Bus','Dublin Bus & Go-Ahead')}${mode('LUAS','Luas','Red & Green lines')}${mode('RAIL','Rail','DART & Commuter')}${mode('WALK','Walk','Door-to-door guidance')}${mode('TAXI','Taxi','Time & fare estimate')}</div></section>
  <section class="quick-live" id="live" aria-labelledby="quick-title"><div><p class="section-number">01 — LIVE DEPARTURES</p><h2 id="quick-title">Know what is coming.<br><em>Before you leave.</em></h2></div><form id="home-stop-form" class="quick-search" novalidate><label for="home-stop-number">Enter the number on the bus stop pole</label><div><span>#</span><input id="home-stop-number" inputmode="numeric" maxlength="8" pattern="[0-9]*" placeholder="${demoMode ? '9999' : '773'}" value="${escapeHtml(state.stop)}" required><button type="submit">Find stop <b>→</b></button></div><small>Your NTA key stays protected on the server.</small></form></section>
  <section class="guide-section" id="guide" aria-labelledby="guide-title"><div class="guide-heading"><div><p class="section-number">02 — ARRIVO GUIDE</p><h2 id="guide-title">Never walk alone.<br><em>Never get lost.</em></h2></div><p>Tell us where you want to go. ArrivoGo will compare the quickest, cheapest and easiest ways across Dublin, all in one place.</p></div><div class="planner-preview"><div class="planner-fields"><div><span class="field-dot start"></span><label>FROM<output>Your current location</output></label></div><span class="field-line"></span><div><span class="field-dot finish"></span><label>TO<output>Where do you want to go?</output></label></div></div><button type="button" class="plan-button" title="Journey planning is the next module">Compare my options <b>→</b></button><div class="planner-options"><span>⚡ Fastest</span><span>€ Cheapest</span><span>♿ Accessible</span><span>◌ Least walking</span></div></div></section>
  <section class="platform" id="platform" aria-labelledby="platform-title"><div class="platform-heading"><div><p class="section-number">03 — THE ARRIVOGO PLATFORM</p><h2 id="platform-title">Built around the <em>whole journey.</em></h2></div><p>Independent tools working together to make Dublin transport clearer, calmer and more dependable.</p></div><div class="module-grid">${modules.map(moduleCard).join('')}</div></section>
  <section class="about-band"><p>BUILT FROM THE DRIVER'S SEAT</p><blockquote>“Real travel experience, turned into a simpler journey for everyone.”</blockquote><span>ArrivoGo is a driver-built Dublin transport platform, shaped by frontline experience helping passengers find the right way every day.</span></section>`;
}

function mode(code,name,detail) { return `<div class="mode"><span>${code}</span><div><strong>${name}</strong><small>${detail}</small></div></div>`; }
function moduleCard([icon,name,copy,status,tone]) { return `<article class="module-card ${tone}"><span class="module-icon">${icon}</span><div><small>${status}</small><h3>${name}</h3><p>${copy}</p></div><span class="module-arrow" aria-hidden="true">↗</span></article>`; }

function liveView() {
  const hasResults = Boolean(state.data), routes = state.data?.routes || [], arrivals = state.data?.arrivals || [], visible = state.showLater ? arrivals : arrivals.slice(0,6), hidden = Math.max(0,arrivals.length-6);
  return `<section class="live-page"><div class="live-page-heading"><button class="back-button" data-view="home">← Home</button><p class="section-number">ARRIVO LIVE</p><h1>Live departures.<br><em>Zero guesswork.</em></h1><p>Official realtime predictions count down. Timetable-only services always show a clock time, clearly labelled Scheduled.</p></div>${hasResults ? activeStopBar() : liveSearch()}${state.verifying ? securityPanel() : ''}${state.error ? `<div class="error-banner" role="alert"><strong>We could not load the board.</strong><span>${escapeHtml(state.error)}</span></div>` : ''}${hasResults ? `<section class="results" aria-live="polite"><div class="results-head"><div><span>NEXT DEPARTURES</span><strong>${escapeHtml(state.data.stop.name)}</strong></div><div class="refresh-block"><span>REFRESH</span><strong>${state.refreshIn}s</strong></div></div><div class="route-filter" aria-label="Choose a route"><button class="route-chip ${state.route === '' ? 'active' : ''}" data-route="">ALL</button>${routes.map(route => `<button class="route-chip ${state.route === route ? 'active' : ''}" data-route="${escapeHtml(route)}">${escapeHtml(route)}</button>`).join('')}</div><div class="board-shell"><div class="board-status"><span><i></i> LIVE + SCHEDULED DEPARTURES</span><time>${formatTime(state.data.refreshedAt)}</time></div><div class="board-header"><span>ROUTE</span><span>DESTINATION</span><span>TIME</span></div><div class="arrival-board">${arrivals.length ? visible.map(arrivalRow).join('') : '<div class="empty-state"><strong>No departures for this selection.</strong><span>Choose ALL or check again after the next refresh.</span></div>'}</div>${hidden > 0 || state.showLater ? `<button id="toggle-later" class="later-toggle" aria-expanded="${state.showLater}"><span>${state.showLater ? '↑' : '↓'}</span><strong>${state.showLater ? 'Show next six only' : `Show ${hidden} later services`}</strong></button>` : ''}<div class="board-footer"><span>Updated ${formatTime(state.data.refreshedAt)}</span><button id="manual-refresh" ${state.loading ? 'disabled' : ''}>Refresh now</button></div></div></section>` : ''}</section>`;
}
function liveSearch() { return `<form id="stop-form" class="live-search" novalidate><label for="stop-number"><span>BUS STOP NUMBER</span><small>Numbers only</small></label><div><span>#</span><input id="stop-number" inputmode="numeric" maxlength="8" pattern="[0-9]*" placeholder="${demoMode ? '9999' : '773'}" value="${escapeHtml(state.stop)}" required><button type="submit" ${state.loading ? 'disabled' : ''}>${state.loading ? 'Checking…' : 'Find departures →'}</button></div><p>Secure live data. Your NTA key never leaves the server.</p></form>`; }
function activeStopBar() { return `<section class="active-stop-bar"><div><span>STOP ${escapeHtml(state.data.stop.code)}</span><strong>${escapeHtml(state.data.stop.name)}</strong></div><button id="change-stop">Change stop</button></section>`; }
function securityPanel() { return '<section class="security-panel" aria-live="polite"><span>✓</span><div><strong>One quick security check</strong><p>This protects live arrivals. No account is needed.</p><div id="turnstile-container"></div></div></section>'; }
function arrivalRow(item) {
  const cancelled=item.status==='Cancelled', live=item.source==='realtime'&&item.realtime!==false, scheduled=formatScheduledTime(item.eta), value=cancelled?'CANCELLED':live?(item.minutes===0?'DUE':String(item.minutes).padStart(2,'0')):scheduled, unit=cancelled||!live||item.minutes===0?'':'MIN', status=live?item.status:'Scheduled', detail=live?(item.vehicleId?`Bus ${escapeHtml(item.vehicleId)}`:escapeHtml(item.agencyName||'Live prediction')):'Timetable only · no live tracking';
  return `<article class="arrival-row ${live?'arrival-live':'arrival-scheduled'}"><div class="route-badge">${escapeHtml(item.route)}</div><div class="destination"><strong>${escapeHtml(item.destination)}</strong><span>${detail}</span></div><div class="arrival-time"><div class="time-display ${cancelled?'cancelled':''}"><strong>${value}</strong>${unit?`<small>${unit}</small>`:''}</div><span class="status">${escapeHtml(status)}</span></div></article>`;
}
function footer() { return `<footer><a class="brand footer-brand" href="#" data-view="home"><span class="brand-mark"><span></span></span><span><strong>ARRIVO<span>GO</span></strong><small>YOUR COMPLETE DUBLIN TRANSPORT COMPANION</small></span></a><p>Independent passenger platform · Live data supplied by the National Transport Authority.</p><p>© ${new Date().getFullYear()} ArrivoGo</p></footer>`; }

function bindEvents() {
  document.querySelectorAll('[data-view]').forEach(control=>control.addEventListener('click',event=>{event.preventDefault();state.view=control.dataset.view;state.error='';render();window.scrollTo({top:0,behavior:'smooth'});}));
  document.querySelector('#home-stop-form')?.addEventListener('submit',event=>{event.preventDefault();state.stop=document.querySelector('#home-stop-number').value.trim();state.view='live';submitStop();});
  document.querySelector('#stop-form')?.addEventListener('submit',event=>{event.preventDefault();state.stop=document.querySelector('#stop-number').value.trim();submitStop();});
  document.querySelectorAll('[data-route]').forEach(button=>button.addEventListener('click',async()=>{state.route=button.dataset.route||'';state.showLater=false;await loadArrivals(false);}));
  document.querySelector('#change-stop')?.addEventListener('click',()=>{state.data=null;state.route='';state.showLater=false;state.error='';render();});
  document.querySelector('#toggle-later')?.addEventListener('click',()=>{state.showLater=!state.showLater;render();});
  document.querySelector('#manual-refresh')?.addEventListener('click',()=>loadArrivals(false));
  document.querySelector('#install-app')?.addEventListener('click',async()=>{state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;render();});
}
function submitStop(){if(!/^\d{1,8}$/.test(state.stop)){state.error='Please enter the numeric stop number printed on the pole.';render();return;}state.route='';state.showLater=false;localStorage.setItem('lastStop',state.stop);loadArrivals();}
async function loadArrivals(resetTimer=true){state.loading=true;state.error='';render();try{await ensureAuthenticated();const params=new URLSearchParams({stop:state.stop});if(state.route)params.set('route',state.route);let response=await fetch(`/api/arrivals?${params}`,{credentials:'same-origin'});if(response.status===401){state.authenticated=false;await ensureAuthenticated(true);response=await fetch(`/api/arrivals?${params}`,{credentials:'same-origin'});}const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'The live service did not respond.');state.data=payload;state.refreshIn=60;if(resetTimer)startRefreshTimer();}catch(error){state.error=error.message||'Unexpected error.';}finally{state.loading=false;state.verifying=false;render();}}
async function ensureAuthenticated(force=false){if(!force&&state.authenticated)return;if(!force){const status=await fetch('/api/session',{credentials:'same-origin'});if(status.ok&&(await status.json()).authenticated){state.authenticated=true;return;}}const token=await getVerificationToken();const response=await fetch('/api/session',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({turnstileToken:token})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Security verification failed.');state.authenticated=true;}
async function getVerificationToken(){if(demoMode&&!turnstileSiteKey)return'local-dev-bypass';if(!turnstileSiteKey)throw new Error('Turnstile is not configured. Add VITE_TURNSTILE_SITE_KEY in Netlify.');state.verifying=true;render();await loadTurnstileScript();return new Promise((resolve,reject)=>{const container=document.querySelector('#turnstile-container');window.turnstile.render(container,{sitekey:turnstileSiteKey,theme:'dark',size:'flexible',action:'passenger_session',callback:resolve,'error-callback':()=>reject(new Error('Security verification could not be completed.'))});});}
function loadTurnstileScript(){if(window.turnstile)return Promise.resolve();return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.defer=true;script.dataset.turnstile='true';script.onload=resolve;script.onerror=reject;document.head.appendChild(script);});}
function startRefreshTimer(){clearInterval(state.timer);state.timer=setInterval(async()=>{state.refreshIn-=1;if(state.refreshIn<=0){state.refreshIn=60;await loadArrivals(false);return;}const counter=document.querySelector('.refresh-block strong');if(counter)counter.textContent=`${state.refreshIn}s`;},1000);}
function formatTime(iso){const date=new Date(iso);return Number.isNaN(date.getTime())?'just now':new Intl.DateTimeFormat('en-IE',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(date);}
function formatScheduledTime(epoch){const date=new Date(Number(epoch)*1000);return Number.isNaN(date.getTime())?'--:--':new Intl.DateTimeFormat('en-IE',{timeZone:'Europe/Dublin',hour:'2-digit',minute:'2-digit',hour12:false}).format(date);}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();state.installPrompt=event;render();});window.addEventListener('appinstalled',()=>{state.installPrompt=null;render();});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));render();
